//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AicaDocsUI.Resources.Pages.Reports.Reason {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AicaDocsUI.Resources.Pages.Reports.Reason.Index.es", typeof(Index_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Razón.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cbtn {
            get {
                return ResourceManager.GetString("cbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí, estoy seguro.
        /// </summary>
        internal static string confbtn {
            get {
                return ResourceManager.GetString("confbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        internal static string exp {
            get {
                return ResourceManager.GetString("exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Razones de Descarga.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea eliminar?.
        /// </summary>
        internal static string q {
            get {
                return ResourceManager.GetString("q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La eliminación falla si se encuentra en uso.
        /// </summary>
        internal static string qE {
            get {
                return ResourceManager.GetString("qE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón de Descarga.
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón de descarga creado con éxito.
        /// </summary>
        internal static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón de descarga actualizado con éxito.
        /// </summary>
        internal static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón de descarga eliminado con éxito.
        /// </summary>
        internal static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón de descarga no puede ser eliminada por estar en uso.
        /// </summary>
        internal static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la razón de descarga se encuentra en uso.
        /// </summary>
        internal static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
    }
}
